### ISSUE TITLE
use postcss for parsing

### ISSUE THREAD

**Issue by MoOx** [ecomfe/node-csshint#1]
Seems a good & robust choice that will allow to check whitespace too (for jscs equivalent).
https://github.com/postcss/postcss

I'm interested to contribute to this project since csslint seems deprecated to me.

**Comment by ielgnaw** [comment]
hi，@MoOx 
I had inspected the [csscomb.js](https://github.com/csscomb/csscomb.js) and [parserlib](https://github.com/CSSLint/parser-lib). Of course, I also investigated [Gonzales](https://github.com/css/gonzales) before, I will see [postcss](https://github.com/postcss/postcss)' sourcecode to see if it is applicable to this project, our project based on our [specification](https://github.com/ecomfe/spec/blob/master/css-style-guide.md). If you are interested, you can also contribute code to this together with me.

**Comment by yisibl** [comment]
PostCSS +1

试试吧！

**Comment by MoOx** [comment]
FYI, I've launched a project for a modern css linter that will use postcss http://stylelint.github.io/

**Comment by ielgnaw** [comment]
Since the 0.1.0 version use [postcss](https://github.com/postcss/postcss) to parse CSS. [PostCSS](https://github.com/postcss/postcss) plug-in mechanism is very powerful.
