### ISSUE TITLE
Add English document

### ISSUE THREAD

**Issue by yisibl** [ecomfe/node-csshint#2]
> PostCSS plugins must have their README.md written in English. Do not be afraid of your English skills, as the open source community will fix your errors.  
> Of course, you are welcome to write documentation in other languages; just name them appropriately (e.g. README.ja.md).
> https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#41-document-your-plugin-in-english

**Comment by ai** [comment]
:D

**Comment by ielgnaw** [comment]
sorry for late~~
